rails_host:
  host: "http://railstutorial.org/"
  ruby_on_rails: "http://news.railstutorial.org/"
users:
  expired_time: 2
  name:
    min_length: 5
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
    max_length: 32
    regex: !ruby/regexp '/[A-Z][a-z]\d/i'
  paging:
    num_per_page: 5
microposts:
  default_size: 50
  picture_size: "300x150"
  max_size: 5
  content:
    max_length: 140
  paging:
    num_per_page: 10
remember_me: "1"
shared:
  micropost_form:
    row: 5